### ISSUE TITLE
添加realm一直报错

### ISSUE THREAD

**Issue by bigdots** [electron-vite/create-electron-vite#10]
我使用了该项目的react模板，但是我安装完realm后，出现报错：
![image](https://user-images.githubusercontent.com/12391404/222717172-4b097ac6-7aa0-4341-a540-8e664247d4a2.png)

系统：windows10

![image](https://user-images.githubusercontent.com/12391404/222717481-34bd63ef-359d-4614-93fc-1de0b7752591.png)

麻烦看一下是不是配置不兼容，谢谢

**Comment by caoxiemeihao** [comment]
你这个在主进程中用还是在渲染进程中用，说不清楚就提供下复现仓库

**Comment by caoxiemeihao** [comment]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/26263658/222869830-af3e9f36-05cc-4913-8018-e4bcbe76cc4c.png">
放到这里
