### ISSUE TITLE
Release a new version to ship customize project name

### ISSUE THREAD

**Issue by fi3ework** [electron-vite/create-electron-vite#11]
See context here https://github.com/vitejs/vite/issues/12288.
I think it's a good boilerplate for Vite x Electron application. While before adding this to `Others` in create-vite. https://github.com/electron-vite/create-electron-vite/pull/8 need to be shipped to customize TARGET_DIR

**Comment by caoxiemeihao** [comment]
`create-electron-vite@0.2.0` is out!

**Comment by fi3ework** [comment]
Will it be changed to the Electron official scaffold after electron/forge v6.1.0?

**Comment by caoxiemeihao** [comment]
No, Electron's official scaffolding does not necessarliy match the user;s habits, it has certain constraints.
At present, electron-vite organization is more in line with what the Vite community is used to.

**Comment by caoxiemeihao** [comment]
@fi3ework da lao shi zai bei jing ma? neng ren shi xia da lao ma?

**Comment by fi3ework** [comment]
> @fi3ework da lao shi zai bei jing ma? neng ren shi xia da lao ma?

You can send an e-mail to me if needed.
