### ISSUE TITLE
Fully based on `create-vite` template

### ISSUE THREAD

**Issue by caoxiemeihao** [electron-vite/create-electron-vite#17]
https://github.com/electron-vite/electron-vite-vue/issues/364

Currently [electron-vite-vue](https://github.com/electron-vite/electron-vite-vue), [electron-vite-react](https://github.com/electron-vite/electron-vite-react) have some opinionated boilerplate code, maybe we should refactor `create-electron-vite` completely based on the latest `create-vite` template and insert only the necessary code snippests.

**Comment by caoxiemeihao** [comment]
@watonyweng 👋
It is planned that the next release will have built-in templates that are consistent with those of `create-vite`.
This design makes it easy to have them compared to the templates in `create-vite` via CI, and then automatically submit a PR if they are not the same.
We will minimally modify the content of the templates when the user selects one, inserting the `vite-plugin-electron` plugin and the corresponding Electron-related code.

计划下一个版本将内置模板，它们与 `create-vite` 的模板保持一致。
这样的设计可以使得我们很容易的通过 CI 让它们与 `create-vite` 中的模板进行对比，然后自动提交 PR 如果它们不相同。
我们将会在用户选择某一个模板时候，最小化修改模板的内容，插入 `vite-plugin-electron` 插件以及对应的 Electron 相关的代码。

```diff
  ├── __test__
  ├── src
+ ├── template-react-ts
+ ├── template-vanilla-ts
+ ├── template-vue-ts
```

**Comment by so1ve** [comment]
How about: we fork create-vite and patch the create script and the templates, and rebase the Upstream daily?

**Comment by caoxiemeihao** [comment]
> How about: we fork create-vite and patch the create script and the templates, and rebase the upstream daily?

Yes, I think it should, but I'm not good with CI not sure if it works.
