### ISSUE TITLE
0.3.0版本程序无法完全退出

### ISSUE THREAD

**Issue by saionjisekai** [electron-vite/create-electron-vite#21]
版本：0.3.0
问题：`electron/main.ts`中`window-all-closed`事件不再执行`app.quit()`，导致程序进程无法完全退出，请问是正常的吗？

**Comment by caoxiemeihao** [comment]
这个要是有问题也应该是 Electron 的问题，electron-vite 只是提供了样板代码而已。

**Comment by saionjisekai** [comment]
已PR(#22)😃
