### ISSUE TITLE
Debug Config

### ISSUE THREAD

**Issue by SnekCode** [electron-vite/create-electron-vite#28]
Hello, I've been banging my head against the wall trying to find out how to configure this project for debugging in VSCode.

Steps to reproduce: `npm create electron-vite debugtest` > choose `react`

I've tried following the guide from https://electron-vite.org/guide/debugging but it is not catching on the break points.

I also stumbled across this issue on the vite-plugin-electron repo https://github.com/electron-vite/vite-plugin-electron/issues/29

I'm starting to regret my tech stack choices 🤣

**Comment by caoxiemeihao** [comment]
Maybe the https://github.com/electron-vite/electron-vite-react is better for you.
