### ISSUE TITLE
preload.ts withPrototype only works on enumerable properties (possibly electron 29.0.0-alpha7 related)

### ISSUE THREAD

**Issue by sparecycles** [electron-vite/create-electron-vite#30]
The example process for exposing the ipcRenderer does not handle non-enumerable properties, leading to `window.ipcRenderer.invoke` being undefined outside of `preload.ts`.

The problem is the use of `Object.entries` to determine properties to expose here

https://github.com/electron-vite/create-electron-vite/blob/a9e13aebc3f628dfcd6d645480e588faf4674735/electron/preload.ts#L8-L11

I suggest replacing `Object.entries` with `Object.getOwnPropertyNames` to address this.

```ts
  const protos = Object.getPrototypeOf(obj)

  for (const key of Object.getOwnPropertyNames(protos)) {
    if (Object.prototype.hasOwnProperty.call(obj, key)) continue
    const value = protos[key];
```

Although, arguably, the base code shouldn't be exposing the ipcRenderer like this, as per the security considerations note in
https://www.electronjs.org/docs/latest/tutorial/ipc

**Comment by caoxiemeihao** [comment]
> Although, arguably, the base code shouldn't be exposing the ipcRenderer like this, as per the security considerations note in
https://www.electronjs.org/docs/latest/tutorial/ipc

Yeah. This code snippets seems a bit hack and not safe enough. 👍
