### ISSUE TITLE
Build app does not load properly pnpm run build

### ISSUE THREAD

**Issue by shuzihao** [electron-vite/create-electron-vite#31]
1.pnpm create electron-vite@latest electron-vite-project.
2. pnpm install
3. pnpm run build
ENOENT: no such file or directory, rename 'D:\git\electron-vite-test1\release\0.0.0\win-unpacked\electron.exe' -> 'D:\git\electron-vite-test1\release\0.0.0\win-unpacked\YourAppName.exe'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, rename 'D:\git\electron-vite-test1\release\0.0.0\win-unpacked\electron.exe' -> 'D:\git\electron-vite-test1\release\0.0.0\win-unpacked\YourAppName.exe'

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-vue/blob/v2.2.0/.npmrc#L3
<img width="818" alt="image" src="https://github.com/electron-vite/create-electron-vite/assets/26263658/bca1e320-2b43-4207-b9a4-62d23f77ae64">
