### ISSUE TITLE
The default Zoom Out keyboard shortcut does not work on MacOS for all templates

### ISSUE THREAD

**Issue by jackhodkinson** [electron-vite/create-electron-vite#36]
Problem: The default electron "Zoom Out" menu command's keyboard shortcut (`command-minus`) does not work on MacOS (found in the default `View` menu).

Steps to reproduce:
1. Create a new project `npm create @quick-start/electron@latest`
2. Follow all vanilla options (or any other options)
3. Install dependencies and run project
4. Press the keyboard shortcut `command-minus` -> nothing happens.

Observations:
- Clicking the menu item "Zoom Out" does work, it's just the keyboard shortcut that does not.
- The default "Zoom In" and "Actual Size"  keyboard shortcuts work as expected.
- I've reproduced this on other machines.
- Other setup tools like `create-electron-app` from [Electron Forge](https://www.electronforge.io/) have the command working by default (including with their `vite` template).

My setup:
- `electron: ^29.2.0`
- `electron-vite: ^2.0.0`
- `npm: 8.5.2`

**Comment by jackhodkinson** [comment]
Update!

I have found that uncommenting these lines restores the zoom out shortcut

```javascript
app.on('browser-window-created', (_, window) => {
  optimizer.watchWindowShortcuts(window)
})
```

**Comment by caoxiemeihao** [comment]
`@quick-start/electron` has no relation to this project(`create-electron-vite`).
