### ISSUE TITLE
npm i 执行报错

### ISSUE THREAD

**Issue by bigdots** [electron-vite/create-electron-vite#4]
npm ERR! code 1
npm ERR! path D:\workspace\code\self\electron-app\electron-vite-vue\node_modules\electron
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! Error: Cannot find module 'got'

**Comment by caoxiemeihao** [comment]
把 `node_modules` 删了，然后配置下 `electron` 下载镜像重新试试
