### ISSUE TITLE
when i use vite5 "type": "module"，how to use better-sqlite3？

### ISSUE THREAD

**Issue by myface-wang** [electron-vite/create-electron-vite#41]
![image](https://github.com/electron-vite/create-electron-vite/assets/13325359/c3e8f48b-9686-4784-9725-bd5e6d300916)

**Comment by NeViNez** [comment]
the solution for me was to import better-sqlite3 after `createRequire()` statement this way:
```
import Database = require('better-sqlite3');
```
However, linter says that `Import assignment cannot be used when targeting ECMAScript modules`, but the app works anyway.

**Comment by myface-wang** [comment]
I have solved it, better-sqlite3 needs to be build before it can be used
