### ISSUE TITLE
build fails on vue template from `create-electron-vite`

### ISSUE THREAD

**Issue by hi-ogawa** [electron-vite/create-electron-vite#47]
Just in case, I'm sharing an issue from Vite https://github.com/vitejs/vite/issues/17881 since currently `create-vite` delegates to `create-electron-vite` when users choose Electron option.

I think this is fixed by `vue-tsc` update https://github.com/electron-vite/create-electron-vite/commit/c558a43df304bc74925808effddcc0ce1739951d, but it looks like the latest 0.7.1 has not been published yet.

```sh
$ npm view create-electron-vite versions
[
  '0.0.0', '0.0.1', '0.0.2',
  '0.0.3', '0.0.4', '0.0.5',
  '0.0.6', '0.0.7', '0.1.0',
  '0.1.1', '0.2.0', '0.2.1',
  '0.2.2', '0.2.3', '0.3.0',
  '0.4.0', '0.5.0', '0.5.1',
  '0.5.2', '0.6.0', '0.7.0'
]
```

**Comment by watonyweng** [comment]
Hi @hi-ogawa ,sorry for getting back to you only now. [0.7.1](https://github.com/electron-vite/create-electron-vite/releases/tag/v0.7.1) has been released, but it hasn't been released to npm yet. I'm trying to figure it out.
